name: Script Execution Cron

on:
  schedule:
    - cron: '30 2 * * 0'  # Runs every Sunday at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  setup_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use a specific, stable version

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found, skipping dependencies"; fi

      - name: Execute Python script
        run: python main.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
